#!/usr/bin/env node
/* share-data.mjs   (save it as scripts/share-data.mjs)

   Makes WhatsApp / Telegram / Facebook link previews work.

   1. Writes api/_share-data.js  (scheme titles + benefits in all four
      languages, read from src/catalogue.js and src/i18n.js)
   2. Adds the preview tags (og:title, og:image ...) to index.html, between
      <!-- share-preview:start --> and <!-- share-preview:end -->.
      Running it again only replaces that block.

   Run it from the project folder, and again whenever scheme text changes:
     node scripts/share-data.mjs

   Different domain?   SITE_URL=https://example.com node scripts/share-data.mjs
*/
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const SITE = (process.env.SITE_URL || "https://hackarena-nine.vercel.app").replace(/\/+$/, "");

class UserError extends Error {}
const fail = (msg) => {
  throw new UserError(msg);
};

const here = path.dirname(fileURLToPath(import.meta.url));
let tmp = null;

function cleanup() {
  if (!tmp) return;
  try {
    fs.rmSync(tmp, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
  } catch {
    /* a leftover temp folder is harmless */
  }
}

function findRoot() {
  for (const start of [process.cwd(), here]) {
    let dir = start;
    for (let i = 0; i < 5; i++) {
      if (fs.existsSync(path.join(dir, "src", "i18n.js"))) return dir;
      const up = path.dirname(dir);
      if (up === dir) break;
      dir = up;
    }
  }
  return null;
}

async function load(root, file, transform = (x) => x) {
  const p = path.join(root, file);
  if (!fs.existsSync(p)) fail(`${file} was not found in ${root}`);
  const out = path.join(tmp, path.basename(file, path.extname(file)) + ".mjs");
  fs.writeFileSync(out, transform(fs.readFileSync(p, "utf8").replace(/^\uFEFF/, "")), "utf8");
  try {
    return await import(pathToFileURL(out).href);
  } catch (e) {
    return fail(`${file} could not be loaded: ${e.message}`);
  }
}

const stubIcons = (src) =>
  src.replace(/import\s*\{([^}]*)\}\s*from\s*["']lucide-react["'];?/g, (m, names) =>
    "const " +
    names.split(",").map((n) => n.trim()).filter(Boolean).map((n) => `${n}=0`).join(",") +
    ";"
  );

const escAttr = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const START = "<!-- share-preview:start -->";
const END = "<!-- share-preview:end -->";

async function main() {
  const root = findRoot();
  if (!root) {
    fail(
      "Could not find the project folder (a folder that has src/i18n.js).\n" +
        "Open PowerShell in your project folder and run:  node scripts/share-data.mjs"
    );
  }
  console.log("project: " + root);
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), "thunai-share-"));

  const i18n = await load(root, "src/i18n.js");
  const cat = await load(root, "src/catalogue.js", stubIcons);
  for (const [mod, names, file] of [
    [i18n, ["T", "LANGS", "BRAND"], "src/i18n.js"],
    [cat, ["S"], "src/catalogue.js"],
  ]) {
    const missing = names.filter((n) => !(n in mod));
    if (missing.length) fail(`${file} does not export: ${missing.join(", ")}. Use the latest version.`);
  }
  const { T, LANGS, BRAND } = i18n;
  const { S } = cat;
  const ids = LANGS.map((x) => x.id);

  // ---------- 1. api/_share-data.js ----------
  const data = { site: SITE, brand: {}, notOfficial: {}, hero: {}, schemes: {} };
  for (const l of ids) {
    if (!T[l].notOfficial || !T[l].hero) fail(`src/i18n.js (${l}) is missing notOfficial or hero. Use the latest i18n.js.`);
    data.brand[l] = BRAND[l];
    data.notOfficial[l] = T[l].notOfficial;
    data.hero[l] = T[l].hero.replace(/[.\s]+$/, "");
  }
  for (const s of S) {
    data.schemes[s.id] = {};
    for (const l of ids) data.schemes[s.id][l] = { title: s[l].title, benefit: s[l].benefit };
  }
  const apiDir = path.join(root, "api");
  fs.mkdirSync(apiDir, { recursive: true });
  fs.writeFileSync(
    path.join(apiDir, "_share-data.js"),
    "// Generated by scripts/share-data.mjs. Do not edit by hand.\n" +
      "export default " + JSON.stringify(data, null, 1) + ";\n",
    "utf8"
  );
  console.log(`wrote api/_share-data.js  (${S.length} schemes, ${ids.length} languages)`);

  // ---------- 2. index.html preview tags ----------
  const htmlPath = path.join(root, "index.html");
  if (!fs.existsSync(htmlPath)) fail("index.html was not found in the project folder.");
  let html = fs.readFileSync(htmlPath, "utf8");

  const outside = html.includes(START) && html.includes(END)
    ? html.slice(0, html.indexOf(START)) + html.slice(html.indexOf(END) + END.length)
    : html;
  const hasDescription = /<meta[^>]+name=["']description["']/i.test(outside);
  const hasThemeColor = /<meta[^>]+name=["']theme-color["']/i.test(outside);
  if (/property=["']og:/i.test(outside)) {
    console.log("note: index.html already has og: tags outside the managed block; remove them to avoid duplicates.");
  }

  const title = `${BRAND.ta} | ${BRAND.en}`;
  const desc =
    "Find government schemes for women in Tamil, English, Hindi and Telugu. " +
    "Speak or type your question. Not an official government website.";

  const tags = [
    START,
    !hasDescription && `<meta name="description" content="${escAttr(desc)}" />`,
    !hasThemeColor && `<meta name="theme-color" content="#9a3412" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="${escAttr(title)}" />`,
    `<meta property="og:title" content="${escAttr(title)}" />`,
    `<meta property="og:description" content="${escAttr(desc)}" />`,
    `<meta property="og:url" content="${SITE}/" />`,
    `<meta property="og:image" content="${SITE}/og-image.png" />`,
    `<meta property="og:image:type" content="image/png" />`,
    `<meta property="og:image:width" content="1200" />`,
    `<meta property="og:image:height" content="630" />`,
    `<meta property="og:image:alt" content="${escAttr(title)}: Your guide to government schemes" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    END,
  ].filter(Boolean).join("\n    ");

  if (html.includes(START) && html.includes(END)) {
    html = html.slice(0, html.indexOf(START)) + tags + html.slice(html.indexOf(END) + END.length);
  } else {
    const m = html.match(/<\/head>/i);
    if (!m) fail("index.html has no </head>.");
    html = html.slice(0, m.index).replace(/[ \t]*$/, "") + "    " + tags + "\n  " + html.slice(m.index);
  }
  fs.writeFileSync(htmlPath, html, "utf8");
  console.log("updated index.html preview tags");

  const t = html.match(/<title>([\s\S]*?)<\/title>/i);
  console.log(`index.html <title>: ${t ? t[1].trim() : "(none)"}`);

  if (!fs.existsSync(path.join(root, "public", "og-image.png"))) {
    console.log("\nWARNING: public/og-image.png is missing. Copy og-image.png into the public folder.");
  }
  console.log("\ndone. Next: replace vercel.json, api/share.js and src/home.jsx, then deploy.");
}

try {
  await main();
} catch (e) {
  if (e instanceof UserError) console.error("\nERROR: " + e.message + "\n");
  else console.error("\nUnexpected error:", e);
  process.exitCode = 1;
} finally {
  cleanup();
}