// Generated by scripts/share-data.mjs. Do not edit by hand.
export default {
 "site": "https://hackarena-nine.vercel.app",
 "brand": {
  "ta": "மகளிர் துணை",
  "en": "Magalir Thunai",
  "hi": "Magalir Thunai",
  "te": "Magalir Thunai"
 },
 "notOfficial": {
  "ta": "இது அரசு இணையதளம் அல்ல. இது ஒரு உதவிக் கருவி மட்டுமே.",
  "en": "This is not an official government website. It is only a help tool.",
  "hi": "यह सरकारी वेबसाइट नहीं है। यह सिर्फ़ एक सहायक टूल है।",
  "te": "ఇది ప్రభుత్వ వెబ్‌సైట్ కాదు. ఇది కేవలం సహాయక సాధనం."
 },
 "hero": {
  "ta": "உங்களுக்கு கிடைக்கக்கூடிய அரசு திட்டங்களை கண்டுபிடிப்போம்",
  "en": "Find government schemes available to you",
  "hi": "आपके लिए उपलब्ध सरकारी योजनाएँ खोजें",
  "te": "మీకు అందుబాటులో ఉన్న ప్రభుత్వ పథకాలను కనుగొనండి"
 },
 "schemes": {
  "kmut": {
   "ta": {
    "title": "கலைஞர் மகளிர் உரிமைத் தொகை",
    "benefit": "மாதம் 1,000 ரூபாய் வங்கிக் கணக்கில்."
   },
   "en": {
    "title": "Kalaignar Magalir Urimai Thittam",
    "benefit": "Rs 1,000 per month to the bank account."
   },
   "hi": {
    "title": "कलैगनार महिला उरिमै थोगई (KMUT)",
    "benefit": "हर महीने 1,000 रुपये बैंक खाते में।"
   },
   "te": {
    "title": "కలైంజర్ మహిళా ఉరిమై తొగై (KMUT)",
    "benefit": "ప్రతి నెల బ్యాంకు ఖాతాలో 1,000 రూపాయలు."
   }
  },
  "pudhumai": {
   "ta": {
    "title": "புதுமைப் பெண் திட்டம்",
    "benefit": "மாதம் 1,000 ரூபாய்."
   },
   "en": {
    "title": "Pudhumai Penn Scheme",
    "benefit": "Rs 1,000 per month."
   },
   "hi": {
    "title": "पुदुमै पेण योजना",
    "benefit": "हर महीने 1,000 रुपये।"
   },
   "te": {
    "title": "పుదుమై పెణ్ పథకం",
    "benefit": "ప్రతి నెల 1,000 రూపాయలు."
   }
  },
  "pmmvy": {
   "ta": {
    "title": "மாத்ரு வந்தனா யோஜனா (PMMVY)",
    "benefit": "முதல் குழந்தைக்கு 5,000 ரூபாய் இரண்டு தவணையில்."
   },
   "en": {
    "title": "PM Matru Vandana Yojana (PMMVY)",
    "benefit": "Rs 5,000 in two instalments for the first child."
   },
   "hi": {
    "title": "मातृ वंदना योजना (PMMVY)",
    "benefit": "पहले बच्चे के लिए दो किस्तों में 5,000 रुपये।"
   },
   "te": {
    "title": "మాతృ వందన యోజన (PMMVY)",
    "benefit": "మొదటి బిడ్డకు రెండు విడతల్లో 5,000 రూపాయలు."
   }
  },
  "widow": {
   "ta": {
    "title": "ஆதரவற்ற விதவை ஓய்வூதியம்",
    "benefit": "மாதாந்திர ஓய்வூதியம். தொகையை அலுவலகத்தில் உறுதி செய்யுங்கள்."
   },
   "en": {
    "title": "Destitute Widow Pension",
    "benefit": "Monthly pension. Confirm the amount at the office."
   },
   "hi": {
    "title": "निराश्रित विधवा पेंशन",
    "benefit": "मासिक पेंशन। राशि कार्यालय में पक्की कर लें।"
   },
   "te": {
    "title": "నిరాధార వితంతు పింఛను",
    "benefit": "నెలవారీ పింఛను. మొత్తాన్ని కార్యాలయంలో నిర్ధారించుకోండి."
   }
  },
  "deserted": {
   "ta": {
    "title": "ஆதரவற்ற / கைவிடப்பட்ட பெண்கள் ஓய்வூதியம்",
    "benefit": "மாதாந்திர ஓய்வூதியம். தொகையை அலுவலகத்தில் உறுதி செய்யுங்கள்."
   },
   "en": {
    "title": "Destitute / Deserted Women Pension",
    "benefit": "Monthly pension. Confirm the amount at the office."
   },
   "hi": {
    "title": "निराश्रित / परित्यक्ता महिला पेंशन",
    "benefit": "मासिक पेंशन। राशि कार्यालय में पक्की कर लें।"
   },
   "te": {
    "title": "నిరాధార / విడిచిపెట్టబడిన మహిళల పింఛను",
    "benefit": "నెలవారీ పింఛను. మొత్తాన్ని కార్యాలయంలో నిర్ధారించుకోండి."
   }
  },
  "unmarried": {
   "ta": {
    "title": "திருமணமாகாத ஏழைப் பெண்கள் ஓய்வூதியம்",
    "benefit": "மாதாந்திர ஓய்வூதியம். தொகையை அலுவலகத்தில் உறுதி செய்யுங்கள்."
   },
   "en": {
    "title": "Unmarried Poor Women Pension",
    "benefit": "Monthly pension. Confirm the amount at the office."
   },
   "hi": {
    "title": "अविवाहित निर्धन महिला पेंशन",
    "benefit": "मासिक पेंशन। राशि कार्यालय में पक्की कर लें।"
   },
   "te": {
    "title": "పెళ్లికాని పేద మహిళల పింఛను",
    "benefit": "నెలవారీ పింఛను. మొత్తాన్ని కార్యాలయంలో నిర్ధారించుకోండి."
   }
  },
  "oldage": {
   "ta": {
    "title": "முதியோர் ஓய்வூதியம்",
    "benefit": "மாதாந்திர ஓய்வூதியம். தொகையை அலுவலகத்தில் உறுதி செய்யுங்கள்."
   },
   "en": {
    "title": "Old Age Pension",
    "benefit": "Monthly pension. Confirm the amount at the office."
   },
   "hi": {
    "title": "वृद्धावस्था पेंशन",
    "benefit": "मासिक पेंशन। राशि कार्यालय में पक्की कर लें।"
   },
   "te": {
    "title": "వృద్ధాప్య పింఛను",
    "benefit": "నెలవారీ పింఛను. మొత్తాన్ని కార్యాలయంలో నిర్ధారించుకోండి."
   }
  },
  "disab": {
   "ta": {
    "title": "மாற்றுத்திறனாளி ஓய்வூதியம்",
    "benefit": "மாதாந்திர ஓய்வூதியம். தொகையை அலுவலகத்தில் உறுதி செய்யுங்கள்."
   },
   "en": {
    "title": "Differently-Abled Pension",
    "benefit": "Monthly pension. Confirm the amount at the office."
   },
   "hi": {
    "title": "दिव्यांग पेंशन",
    "benefit": "मासिक पेंशन। राशि कार्यालय में पक्की कर लें।"
   },
   "te": {
    "title": "దివ్యాంగుల పింఛను",
    "benefit": "నెలవారీ పింఛను. మొత్తాన్ని కార్యాలయంలో నిర్ధారించుకోండి."
   }
  },
  "ssy": {
   "ta": {
    "title": "செல்வமகள் சேமிப்புத் திட்டம்",
    "benefit": "பெண் குழந்தையின் பெயரில் சிறு சேமிப்புக் கணக்கு."
   },
   "en": {
    "title": "Sukanya Samriddhi Scheme",
    "benefit": "A small savings account in the girl child's name."
   },
   "hi": {
    "title": "सुकन्या समृद्धि योजना",
    "benefit": "बालिका के नाम पर छोटी बचत खाता।"
   },
   "te": {
    "title": "సుకన్య సమృద్ధి పథకం",
    "benefit": "ఆడపిల్ల పేరుపై చిన్న పొదుపు ఖాతా."
   }
  },
  "payanam": {
   "ta": {
    "title": "வெற்றிப் பயணம் (முன்பு விடியல் பயணம்)",
    "benefit": "அரசுப் பேருந்துகளில் இலவசப் பயணம். வருமான வரம்பு இல்லை."
   },
   "en": {
    "title": "Vettri Payanam (earlier Vidiyal Payanam)",
    "benefit": "Free travel on government buses. No income limit."
   },
   "hi": {
    "title": "वेट्री पयणम (पहले विडियल पयणम)",
    "benefit": "सरकारी बसों में मुफ़्त यात्रा। आय की कोई सीमा नहीं।"
   },
   "te": {
    "title": "వెట్రి పయనం (ఇంతకు ముందు విడియల్ పయనం)",
    "benefit": "ప్రభుత్వ బస్సుల్లో ఉచిత ప్రయాణం. ఆదాయ పరిమితి లేదు."
   }
  },
  "muthulakshmi": {
   "ta": {
    "title": "டாக்டர் முத்துலட்சுமி ரெட்டி மகப்பேறு உதவித் திட்டம்",
    "benefit": "மொத்தம் 18,000 ரூபாய்: 14,000 ரூபாய் பணம் தவணைகளில், மற்றும் 4,000 ரூபாய் மதிப்புள்ள இரண்டு ஊட்டச்சத்துப் பெட்டகங்கள்."
   },
   "en": {
    "title": "Dr. Muthulakshmi Reddy Maternity Assistance Scheme",
    "benefit": "Rs 18,000 in total: Rs 14,000 cash in instalments plus two nutrition kits worth Rs 4,000."
   },
   "hi": {
    "title": "डॉ. मुथुलक्ष्मी रेड्डी मातृत्व सहायता योजना",
    "benefit": "कुल 18,000 रुपये: 14,000 रुपये नकद किस्तों में और 4,000 रुपये के दो पोषण किट।"
   },
   "te": {
    "title": "డాక్టర్ ముత్తులక్ష్మి రెడ్డి మాతృత్వ సహాయ పథకం",
    "benefit": "మొత్తం 18,000 రూపాయలు: 14,000 రూపాయలు విడతల్లో నగదు, 4,000 రూపాయల విలువైన రెండు పోషకాహార కిట్లు."
   }
  },
  "cmgirl": {
   "ta": {
    "title": "முதலமைச்சரின் பெண் குழந்தை பாதுகாப்புத் திட்டம்",
    "benefit": "பெண் குழந்தையின் பெயரில் அரசு வைப்புத் தொகை: ஒரு பெண் குழந்தைக்கு 50,000 ரூபாய், இரண்டு பெண் குழந்தைகளுக்கு தலா 25,000 ரூபாய். 18 வயதில் கிடைக்கும்."
   },
   "en": {
    "title": "Chief Minister's Girl Child Protection Scheme",
    "benefit": "A government fixed deposit in the girl child's name: Rs 50,000 for one girl child, or Rs 25,000 each for two girls. Paid when she turns 18."
   },
   "hi": {
    "title": "मुख्यमंत्री बालिका संरक्षण योजना",
    "benefit": "बालिका के नाम पर सरकारी सावधि जमा: एक बालिका के लिए 50,000 रुपये, दो बालिकाओं के लिए 25,000 रुपये प्रत्येक। 18 साल की उम्र में मिलती है।"
   },
   "te": {
    "title": "ముఖ్యమంత్రి ఆడపిల్ల రక్షణ పథకం",
    "benefit": "ఆడపిల్ల పేరుపై ప్రభుత్వ ఫిక్స్‌డ్ డిపాజిట్: ఒక ఆడపిల్లకు 50,000 రూపాయలు, ఇద్దరు ఆడపిల్లలకు ఒక్కొక్కరికి 25,000 రూపాయలు. 18 ఏళ్లకు లభిస్తుంది."
   }
  },
  "sewing": {
   "ta": {
    "title": "சத்தியவாணிமுத்து அம்மையார் நினைவு இலவச தையல் இயந்திரத் திட்டம்",
    "benefit": "சுயதொழிலுக்கு இலவச தையல் இயந்திரம்."
   },
   "en": {
    "title": "Sathyavani Muthu Ammaiyar Memorial Free Sewing Machine Scheme",
    "benefit": "A free sewing machine for self-employment."
   },
   "hi": {
    "title": "सत्यवाणी मुत्तु अम्मैयार स्मृति निःशुल्क सिलाई मशीन योजना",
    "benefit": "स्वरोज़गार के लिए निःशुल्क सिलाई मशीन।"
   },
   "te": {
    "title": "సత్యవాణి ముత్తు అమ్మైయార్ స్మారక ఉచిత కుట్టు యంత్ర పథకం",
    "benefit": "స్వయం ఉపాధికి ఉచిత కుట్టు యంత్రం."
   }
  }
 }
};
